(define (domain generated_domain) 
 (:requirements :strips :typing )
(:types location image )
(:predicates (clear ?0 - location)
(at ?0 - image ?1 - location)
(changed_together_link ?0 - location ?1 - location)
(depends_on_3 ?0 - object ?1 - object ?2 - object)
(depends_on_2 ?0 - object ?1 - object)
(depends_on_4 ?0 - object ?1 - object ?2 - object ?3 - object)
)


;------------------------------------------------------------------
; for middle blocks:
(:action action_2
 :parameters ( ?0 - location ?1 - location ?2 - location ?3 - location ?4 - location ?5 - location ?6 - image ?7 - image ?8 - image) 
 :precondition (and (at ?6 ?0)
 ( not (clear ?0))
 (changed_together_link ?0 ?2)
 (changed_together_link ?2 ?0)
 (depends_on_3 ?0 ?4 ?5)
 (depends_on_3 ?0 ?5 ?4)
 ( not (clear ?1))
 (depends_on_3 ?2 ?1 ?3)
 (depends_on_3 ?2 ?3 ?1)
 (at ?7 ?1)
 ( not (at ?6 ?2))
 (clear ?2)
 (clear ?3)
 (clear ?4)
 ( not (clear ?5))
 (at ?8 ?5)
 (depends_on_3 ?6 ?8 ?7)
 (depends_on_3 ?6 ?7 ?8)
 ) 
 :effect (and ( not (at ?6 ?0))
 (clear ?0)
 (at ?6 ?2)
 ( not (clear ?2))
 ) 
) 


;------------------------------------------------------------------
; one bottom edge (both way round - i.e., block being moved from/to an edge): 

(:action action_0
 :parameters ( ?0 - location ?1 - location ?2 - location ?3 - location ?4 - location ?5 - image ?6 - image) 
 :precondition (and ( not (at ?5 ?0))
 (clear ?0)
 (changed_together_link ?0 ?1)
 (changed_together_link ?1 ?0)
 (depends_on_3 ?0 ?3 ?4)
 (depends_on_3 ?0 ?4 ?3)
 (at ?5 ?1)
 ( not (clear ?1))
 (depends_on_2 ?1 ?2)
 (depends_on_3 ?5 ?6 ?1)
 (depends_on_3 ?5 ?1 ?6)
 (clear ?2)
 (clear ?3)
 ( not (clear ?4))
 (at ?6 ?4)
 ) 
 :effect (and (at ?5 ?0)
 ( not (clear ?0))
 ( not (at ?5 ?1))
 (clear ?1)
 ) 
) 

(:action action_1
 :parameters ( ?0 - location ?1 - location ?2 - location ?3 - location ?4 - location ?5 - image ?6 - image) 
 :precondition (and (clear ?0)
 (depends_on_2 ?4 ?0)
 ( not (clear ?1))
 (depends_on_3 ?2 ?1 ?3)
 (depends_on_3 ?2 ?3 ?1)
 (at ?6 ?1)
 (at ?5 ?2)
 ( not (clear ?2))
 (changed_together_link ?2 ?4)
 (changed_together_link ?4 ?2)
 (clear ?3)
 ( not (at ?5 ?4))
 (clear ?4)
 (depends_on_3 ?5 ?6 ?4)
 (depends_on_3 ?5 ?4 ?6)
 ) 
 :effect (and ( not (at ?5 ?2))
 (clear ?2)
 (at ?5 ?4)
 ( not (clear ?4))
 ) 
) 




;------------------------------------------------------------------
; two bottom edges

(:action action_3
 :parameters ( ?0 - location ?1 - location ?2 - location ?3 - image ?4 - location) 
 :precondition (and (clear ?0)
 (depends_on_2 ?4 ?0)
 ( not (at ?3 ?1))
 (clear ?1)
 (changed_together_link ?1 ?4)
 (changed_together_link ?4 ?1)
 (depends_on_2 ?1 ?2)
 (depends_on_3 ?3 ?1 ?4)
 (depends_on_3 ?3 ?4 ?1)
 (clear ?2)
 (at ?3 ?4)
 ( not (clear ?4))
 ) 
 :effect (and (at ?3 ?1)
 ( not (clear ?1))
 ( not (at ?3 ?4))
 (clear ?4)
 ) 
) 


;------------------------------------------------------------------
; block being moved to/from a top edge (an action can't involve two top edges)

(:action action_4
 :parameters ( ?0 - location ?1 - location ?2 - location ?3 - location ?4 - image ?5 - image) 
 :precondition (and (at ?4 ?0)
 ( not (clear ?0))
 (changed_together_link ?0 ?3)
 (changed_together_link ?3 ?0)
 (depends_on_2 ?0 ?2)
 (depends_on_4 ?4 ?0 ?5 ?5)
 (depends_on_4 ?4 ?5 ?0 ?5)
 (depends_on_4 ?4 ?5 ?5 ?0)
 (at ?5 ?1)
 (depends_on_3 ?3 ?5 ?1)
 (depends_on_3 ?3 ?1 ?5)
 (clear ?2)
 ( not (at ?4 ?3))
 (clear ?3)
 ) 
 :effect (and ( not (at ?4 ?0))
 (clear ?0)
 (at ?4 ?3)
 ( not (clear ?3))
 ) 
) 

;---------------------------------------

(:action action_5
 :parameters ( ?0 - location ?1 - location ?2 - location ?3 - location ?4 - image ?5 - image) 
 :precondition (and ( not (at ?4 ?0))
 (clear ?0)
 (changed_together_link ?0 ?3)
 (changed_together_link ?3 ?0)
 (depends_on_2 ?0 ?1)
 (depends_on_4 ?4 ?0 ?5 ?5)
 (depends_on_4 ?4 ?5 ?0 ?5)
 (depends_on_4 ?4 ?5 ?5 ?0)
 (clear ?1)
 (at ?5 ?2)
 (depends_on_3 ?3 ?5 ?2)
 (depends_on_3 ?3 ?2 ?5)
 (at ?4 ?3)
 ( not (clear ?3))
 ) 
 :effect (and (at ?4 ?0)
 ( not (clear ?0))
 ( not (at ?4 ?3))
 (clear ?3)
 ) 
) 


)
