(define (problem generated_problem)
(:domain generated_domain) 
 (:objects 
location_0 - location 
  location_1 - location 
  location_2 - location 
  location_3 - location 
  location_4 - location 
  location_5 - location 
  location_6 - location 
  location_7 - location 
  location_8 - location 
  image_9 - image 
  )
 (:init 
(changed_together_link_3 location_0 location_1 location_2)
(changed_together_link_3 location_0 location_2 location_1)
(changed_together_link_3 location_1 location_0 location_2)
(changed_together_link_3 location_1 location_2 location_0)
(changed_together_link_3 location_2 location_0 location_1)
(changed_together_link_3 location_2 location_1 location_0)
(changed_together_link_4 location_0 location_1 location_3 location_4)
(changed_together_link_4 location_0 location_1 location_4 location_3)
(changed_together_link_4 location_0 location_3 location_1 location_4)
(changed_together_link_4 location_0 location_3 location_4 location_1)
(changed_together_link_4 location_0 location_4 location_1 location_3)
(changed_together_link_4 location_0 location_4 location_3 location_1)
(changed_together_link_4 location_1 location_0 location_3 location_4)
(changed_together_link_4 location_1 location_0 location_4 location_3)
(changed_together_link_4 location_1 location_3 location_0 location_4)
(changed_together_link_4 location_1 location_3 location_4 location_0)
(changed_together_link_4 location_1 location_4 location_0 location_3)
(changed_together_link_4 location_1 location_4 location_3 location_0)
(changed_together_link_4 location_3 location_0 location_1 location_4)
(changed_together_link_4 location_3 location_0 location_4 location_1)
(changed_together_link_4 location_3 location_1 location_0 location_4)
(changed_together_link_4 location_3 location_1 location_4 location_0)
(changed_together_link_4 location_3 location_4 location_0 location_1)
(changed_together_link_4 location_3 location_4 location_1 location_0)
(changed_together_link_4 location_4 location_0 location_1 location_3)
(changed_together_link_4 location_4 location_0 location_3 location_1)
(changed_together_link_4 location_4 location_1 location_0 location_3)
(changed_together_link_4 location_4 location_1 location_3 location_0)
(changed_together_link_4 location_4 location_3 location_0 location_1)
(changed_together_link_4 location_4 location_3 location_1 location_0)
(changed_together_link_3 location_0 location_4 location_5)
(changed_together_link_3 location_0 location_5 location_4)
(changed_together_link_3 location_4 location_0 location_5)
(changed_together_link_3 location_4 location_5 location_0)
(changed_together_link_3 location_5 location_0 location_4)
(changed_together_link_3 location_5 location_4 location_0)
(changed_together_link_4 location_1 location_2 location_3 location_6)
(changed_together_link_4 location_1 location_2 location_6 location_3)
(changed_together_link_4 location_1 location_3 location_2 location_6)
(changed_together_link_4 location_1 location_3 location_6 location_2)
(changed_together_link_4 location_1 location_6 location_2 location_3)
(changed_together_link_4 location_1 location_6 location_3 location_2)
(changed_together_link_4 location_2 location_1 location_3 location_6)
(changed_together_link_4 location_2 location_1 location_6 location_3)
(changed_together_link_4 location_2 location_3 location_1 location_6)
(changed_together_link_4 location_2 location_3 location_6 location_1)
(changed_together_link_4 location_2 location_6 location_1 location_3)
(changed_together_link_4 location_2 location_6 location_3 location_1)
(changed_together_link_4 location_3 location_1 location_2 location_6)
(changed_together_link_4 location_3 location_1 location_6 location_2)
(changed_together_link_4 location_3 location_2 location_1 location_6)
(changed_together_link_4 location_3 location_2 location_6 location_1)
(changed_together_link_4 location_3 location_6 location_1 location_2)
(changed_together_link_4 location_3 location_6 location_2 location_1)
(changed_together_link_4 location_6 location_1 location_2 location_3)
(changed_together_link_4 location_6 location_1 location_3 location_2)
(changed_together_link_4 location_6 location_2 location_1 location_3)
(changed_together_link_4 location_6 location_2 location_3 location_1)
(changed_together_link_4 location_6 location_3 location_1 location_2)
(changed_together_link_4 location_6 location_3 location_2 location_1)
(changed_together_link_5 location_0 location_2 location_3 location_5 location_7)
(changed_together_link_5 location_0 location_2 location_3 location_7 location_5)
(changed_together_link_5 location_0 location_2 location_5 location_3 location_7)
(changed_together_link_5 location_0 location_2 location_5 location_7 location_3)
(changed_together_link_5 location_0 location_2 location_7 location_3 location_5)
(changed_together_link_5 location_0 location_2 location_7 location_5 location_3)
(changed_together_link_5 location_0 location_3 location_2 location_5 location_7)
(changed_together_link_5 location_0 location_3 location_2 location_7 location_5)
(changed_together_link_5 location_0 location_3 location_5 location_2 location_7)
(changed_together_link_5 location_0 location_3 location_5 location_7 location_2)
(changed_together_link_5 location_0 location_3 location_7 location_2 location_5)
(changed_together_link_5 location_0 location_3 location_7 location_5 location_2)
(changed_together_link_5 location_0 location_5 location_2 location_3 location_7)
(changed_together_link_5 location_0 location_5 location_2 location_7 location_3)
(changed_together_link_5 location_0 location_5 location_3 location_2 location_7)
(changed_together_link_5 location_0 location_5 location_3 location_7 location_2)
(changed_together_link_5 location_0 location_5 location_7 location_2 location_3)
(changed_together_link_5 location_0 location_5 location_7 location_3 location_2)
(changed_together_link_5 location_0 location_7 location_2 location_3 location_5)
(changed_together_link_5 location_0 location_7 location_2 location_5 location_3)
(changed_together_link_5 location_0 location_7 location_3 location_2 location_5)
(changed_together_link_5 location_0 location_7 location_3 location_5 location_2)
(changed_together_link_5 location_0 location_7 location_5 location_2 location_3)
(changed_together_link_5 location_0 location_7 location_5 location_3 location_2)
(changed_together_link_5 location_2 location_0 location_3 location_5 location_7)
(changed_together_link_5 location_2 location_0 location_3 location_7 location_5)
(changed_together_link_5 location_2 location_0 location_5 location_3 location_7)
(changed_together_link_5 location_2 location_0 location_5 location_7 location_3)
(changed_together_link_5 location_2 location_0 location_7 location_3 location_5)
(changed_together_link_5 location_2 location_0 location_7 location_5 location_3)
(changed_together_link_5 location_2 location_3 location_0 location_5 location_7)
(changed_together_link_5 location_2 location_3 location_0 location_7 location_5)
(changed_together_link_5 location_2 location_3 location_5 location_0 location_7)
(changed_together_link_5 location_2 location_3 location_5 location_7 location_0)
(changed_together_link_5 location_2 location_3 location_7 location_0 location_5)
(changed_together_link_5 location_2 location_3 location_7 location_5 location_0)
(changed_together_link_5 location_2 location_5 location_0 location_3 location_7)
(changed_together_link_5 location_2 location_5 location_0 location_7 location_3)
(changed_together_link_5 location_2 location_5 location_3 location_0 location_7)
(changed_together_link_5 location_2 location_5 location_3 location_7 location_0)
(changed_together_link_5 location_2 location_5 location_7 location_0 location_3)
(changed_together_link_5 location_2 location_5 location_7 location_3 location_0)
(changed_together_link_5 location_2 location_7 location_0 location_3 location_5)
(changed_together_link_5 location_2 location_7 location_0 location_5 location_3)
(changed_together_link_5 location_2 location_7 location_3 location_0 location_5)
(changed_together_link_5 location_2 location_7 location_3 location_5 location_0)
(changed_together_link_5 location_2 location_7 location_5 location_0 location_3)
(changed_together_link_5 location_2 location_7 location_5 location_3 location_0)
(changed_together_link_5 location_3 location_0 location_2 location_5 location_7)
(changed_together_link_5 location_3 location_0 location_2 location_7 location_5)
(changed_together_link_5 location_3 location_0 location_5 location_2 location_7)
(changed_together_link_5 location_3 location_0 location_5 location_7 location_2)
(changed_together_link_5 location_3 location_0 location_7 location_2 location_5)
(changed_together_link_5 location_3 location_0 location_7 location_5 location_2)
(changed_together_link_5 location_3 location_2 location_0 location_5 location_7)
(changed_together_link_5 location_3 location_2 location_0 location_7 location_5)
(changed_together_link_5 location_3 location_2 location_5 location_0 location_7)
(changed_together_link_5 location_3 location_2 location_5 location_7 location_0)
(changed_together_link_5 location_3 location_2 location_7 location_0 location_5)
(changed_together_link_5 location_3 location_2 location_7 location_5 location_0)
(changed_together_link_5 location_3 location_5 location_0 location_2 location_7)
(changed_together_link_5 location_3 location_5 location_0 location_7 location_2)
(changed_together_link_5 location_3 location_5 location_2 location_0 location_7)
(changed_together_link_5 location_3 location_5 location_2 location_7 location_0)
(changed_together_link_5 location_3 location_5 location_7 location_0 location_2)
(changed_together_link_5 location_3 location_5 location_7 location_2 location_0)
(changed_together_link_5 location_3 location_7 location_0 location_2 location_5)
(changed_together_link_5 location_3 location_7 location_0 location_5 location_2)
(changed_together_link_5 location_3 location_7 location_2 location_0 location_5)
(changed_together_link_5 location_3 location_7 location_2 location_5 location_0)
(changed_together_link_5 location_3 location_7 location_5 location_0 location_2)
(changed_together_link_5 location_3 location_7 location_5 location_2 location_0)
(changed_together_link_5 location_5 location_0 location_2 location_3 location_7)
(changed_together_link_5 location_5 location_0 location_2 location_7 location_3)
(changed_together_link_5 location_5 location_0 location_3 location_2 location_7)
(changed_together_link_5 location_5 location_0 location_3 location_7 location_2)
(changed_together_link_5 location_5 location_0 location_7 location_2 location_3)
(changed_together_link_5 location_5 location_0 location_7 location_3 location_2)
(changed_together_link_5 location_5 location_2 location_0 location_3 location_7)
(changed_together_link_5 location_5 location_2 location_0 location_7 location_3)
(changed_together_link_5 location_5 location_2 location_3 location_0 location_7)
(changed_together_link_5 location_5 location_2 location_3 location_7 location_0)
(changed_together_link_5 location_5 location_2 location_7 location_0 location_3)
(changed_together_link_5 location_5 location_2 location_7 location_3 location_0)
(changed_together_link_5 location_5 location_3 location_0 location_2 location_7)
(changed_together_link_5 location_5 location_3 location_0 location_7 location_2)
(changed_together_link_5 location_5 location_3 location_2 location_0 location_7)
(changed_together_link_5 location_5 location_3 location_2 location_7 location_0)
(changed_together_link_5 location_5 location_3 location_7 location_0 location_2)
(changed_together_link_5 location_5 location_3 location_7 location_2 location_0)
(changed_together_link_5 location_5 location_7 location_0 location_2 location_3)
(changed_together_link_5 location_5 location_7 location_0 location_3 location_2)
(changed_together_link_5 location_5 location_7 location_2 location_0 location_3)
(changed_together_link_5 location_5 location_7 location_2 location_3 location_0)
(changed_together_link_5 location_5 location_7 location_3 location_0 location_2)
(changed_together_link_5 location_5 location_7 location_3 location_2 location_0)
(changed_together_link_5 location_7 location_0 location_2 location_3 location_5)
(changed_together_link_5 location_7 location_0 location_2 location_5 location_3)
(changed_together_link_5 location_7 location_0 location_3 location_2 location_5)
(changed_together_link_5 location_7 location_0 location_3 location_5 location_2)
(changed_together_link_5 location_7 location_0 location_5 location_2 location_3)
(changed_together_link_5 location_7 location_0 location_5 location_3 location_2)
(changed_together_link_5 location_7 location_2 location_0 location_3 location_5)
(changed_together_link_5 location_7 location_2 location_0 location_5 location_3)
(changed_together_link_5 location_7 location_2 location_3 location_0 location_5)
(changed_together_link_5 location_7 location_2 location_3 location_5 location_0)
(changed_together_link_5 location_7 location_2 location_5 location_0 location_3)
(changed_together_link_5 location_7 location_2 location_5 location_3 location_0)
(changed_together_link_5 location_7 location_3 location_0 location_2 location_5)
(changed_together_link_5 location_7 location_3 location_0 location_5 location_2)
(changed_together_link_5 location_7 location_3 location_2 location_0 location_5)
(changed_together_link_5 location_7 location_3 location_2 location_5 location_0)
(changed_together_link_5 location_7 location_3 location_5 location_0 location_2)
(changed_together_link_5 location_7 location_3 location_5 location_2 location_0)
(changed_together_link_5 location_7 location_5 location_0 location_2 location_3)
(changed_together_link_5 location_7 location_5 location_0 location_3 location_2)
(changed_together_link_5 location_7 location_5 location_2 location_0 location_3)
(changed_together_link_5 location_7 location_5 location_2 location_3 location_0)
(changed_together_link_5 location_7 location_5 location_3 location_0 location_2)
(changed_together_link_5 location_7 location_5 location_3 location_2 location_0)
(changed_together_link_4 location_3 location_4 location_5 location_8)
(changed_together_link_4 location_3 location_4 location_8 location_5)
(changed_together_link_4 location_3 location_5 location_4 location_8)
(changed_together_link_4 location_3 location_5 location_8 location_4)
(changed_together_link_4 location_3 location_8 location_4 location_5)
(changed_together_link_4 location_3 location_8 location_5 location_4)
(changed_together_link_4 location_4 location_3 location_5 location_8)
(changed_together_link_4 location_4 location_3 location_8 location_5)
(changed_together_link_4 location_4 location_5 location_3 location_8)
(changed_together_link_4 location_4 location_5 location_8 location_3)
(changed_together_link_4 location_4 location_8 location_3 location_5)
(changed_together_link_4 location_4 location_8 location_5 location_3)
(changed_together_link_4 location_5 location_3 location_4 location_8)
(changed_together_link_4 location_5 location_3 location_8 location_4)
(changed_together_link_4 location_5 location_4 location_3 location_8)
(changed_together_link_4 location_5 location_4 location_8 location_3)
(changed_together_link_4 location_5 location_8 location_3 location_4)
(changed_together_link_4 location_5 location_8 location_4 location_3)
(changed_together_link_4 location_8 location_3 location_4 location_5)
(changed_together_link_4 location_8 location_3 location_5 location_4)
(changed_together_link_4 location_8 location_4 location_3 location_5)
(changed_together_link_4 location_8 location_4 location_5 location_3)
(changed_together_link_4 location_8 location_5 location_3 location_4)
(changed_together_link_4 location_8 location_5 location_4 location_3)
(changed_together_link_3 location_2 location_6 location_7)
(changed_together_link_3 location_2 location_7 location_6)
(changed_together_link_3 location_6 location_2 location_7)
(changed_together_link_3 location_6 location_7 location_2)
(changed_together_link_3 location_7 location_2 location_6)
(changed_together_link_3 location_7 location_6 location_2)
(changed_together_link_4 location_3 location_6 location_7 location_8)
(changed_together_link_4 location_3 location_6 location_8 location_7)
(changed_together_link_4 location_3 location_7 location_6 location_8)
(changed_together_link_4 location_3 location_7 location_8 location_6)
(changed_together_link_4 location_3 location_8 location_6 location_7)
(changed_together_link_4 location_3 location_8 location_7 location_6)
(changed_together_link_4 location_6 location_3 location_7 location_8)
(changed_together_link_4 location_6 location_3 location_8 location_7)
(changed_together_link_4 location_6 location_7 location_3 location_8)
(changed_together_link_4 location_6 location_7 location_8 location_3)
(changed_together_link_4 location_6 location_8 location_3 location_7)
(changed_together_link_4 location_6 location_8 location_7 location_3)
(changed_together_link_4 location_7 location_3 location_6 location_8)
(changed_together_link_4 location_7 location_3 location_8 location_6)
(changed_together_link_4 location_7 location_6 location_3 location_8)
(changed_together_link_4 location_7 location_6 location_8 location_3)
(changed_together_link_4 location_7 location_8 location_3 location_6)
(changed_together_link_4 location_7 location_8 location_6 location_3)
(changed_together_link_4 location_8 location_3 location_6 location_7)
(changed_together_link_4 location_8 location_3 location_7 location_6)
(changed_together_link_4 location_8 location_6 location_3 location_7)
(changed_together_link_4 location_8 location_6 location_7 location_3)
(changed_together_link_4 location_8 location_7 location_3 location_6)
(changed_together_link_4 location_8 location_7 location_6 location_3)
(changed_together_link_3 location_5 location_7 location_8)
(changed_together_link_3 location_5 location_8 location_7)
(changed_together_link_3 location_7 location_5 location_8)
(changed_together_link_3 location_7 location_8 location_5)
(changed_together_link_3 location_8 location_5 location_7)
(changed_together_link_3 location_8 location_7 location_5)
(clear location_0)
(clear location_1)
( not (clear location_2))
(at image_9 location_2)
( not (clear location_3))
(at image_9 location_3)
(clear location_4)
(clear location_5)
( not (clear location_6))
(at image_9 location_6)
(clear location_7)
(clear location_8)
)
 (:goal (and 
( not (clear location_0))
(at image_9 location_0)
(clear location_1)
(clear location_2)
(clear location_3)
(clear location_4)
(clear location_5)
(clear location_6)
( not (clear location_7))
(at image_9 location_7)
(clear location_8)
) )
)